"""empty message

Revision ID: 5e653b115c98
Revises: 01ad86bca7eb
Create Date: 2023-11-27 11:02:57.226525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e653b115c98'
down_revision = '01ad86bca7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_requests', schema=None) as batch_op:
        batch_op.alter_column('request_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('request_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
