"""empty message

Revision ID: 980a935a0b15
Revises: c4c7d205a16b
Create Date: 2023-11-22 22:05:14.179774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980a935a0b15'
down_revision = 'c4c7d205a16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('release_year',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('create_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('create_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('release_year',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
