"""empty message

Revision ID: e33b9f5b9fb8
Revises: 4e6a3e1ff0f8
Create Date: 2023-11-27 11:46:08.645653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33b9f5b9fb8'
down_revision = '4e6a3e1ff0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_cart_movies_cart_id_carts')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_cart_movies_movie_id_movies')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_movies')
    # ### end Alembic commands ###
